* BotClean Partially Observable
The game Bot Clean took place in a fully observable environment i.e.,
the state of every cell was visible to the bot at all times. Let us
consider a variation of it where the environment is partially
observable. The bot has the same actuators and sensors. But the
sensors visibility is confined to its 8 adjacent cells.

* Input Format

The first line contains two single spaced integers which indicates the
current position of the bot. The grid is indexed (x, y) 0<=x,y<=4 top
to bottom and left to right respectively.

5 lines follow, representing the grid. Each cell in the grid is
represented by any of the following 4 characters. ‘b’ (ascii
value 98) indicates the bot’s current position, ‘d’ (ascii
value 100) indicates a dirty cell, ‘-‘ (ascii value 45) indicates a
clean cell in the grid and ‘o’ (ascii value 111) indicates the cell
that is currently not visible.

* Output Format

Output is the action that is taken by the bot in the current step and
it can be any of the movements in 4 directions or cleaning the cell in
which it is currently located. The output formats are LEFT, RIGHT, UP,
DOWN or CLEAN.

* Sample Input

0 0
b-ooo
-dooo
ooooo
ooooo
ooooo
Sample Output

RIGHT
* Task

Complete the function next_move that takes in 3 parameters posx, posy
being the co-ordinates of the bot’s current position and board which
indicates the board state, and print the bot’s next move.

* Scoring

The goal is to clean all the dirty cells in as few moves as
possible. Your score is 200 - number of bot moves. All bots in this
challenge will be given the same input. CLEAN is also considered a
move.

* Education Links
http://en.wikipedia.org/wiki/PEAS
