/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_freedesktop_DBus_general_api
#define DBUS_GLIB_CLIENT_WRAPPERS_org_freedesktop_DBus_general_api

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_freedesktop_DBus_general_api_client_request (DBusGProxy *proxy, const gint IN_action_id, const gint IN_input_int, const GArray* IN_input_garray, gint* OUT_outut_int, GArray** OUT_output_garray, gint* OUT_result, GError **error)

{
  return dbus_g_proxy_call (proxy, "client_request", error, G_TYPE_INT, IN_action_id, G_TYPE_INT, IN_input_int, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), IN_input_garray, G_TYPE_INVALID, G_TYPE_INT, OUT_outut_int, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), OUT_output_garray, G_TYPE_INT, OUT_result, G_TYPE_INVALID);
}

typedef void (*org_freedesktop_DBus_general_api_client_request_reply) (DBusGProxy *proxy, gint OUT_outut_int, GArray *OUT_output_garray, gint OUT_result, GError *error, gpointer userdata);

static void
org_freedesktop_DBus_general_api_client_request_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gint OUT_outut_int;
  GArray* OUT_output_garray;
  gint OUT_result;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INT, &OUT_outut_int, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), &OUT_output_garray, G_TYPE_INT, &OUT_result, G_TYPE_INVALID);
  (*(org_freedesktop_DBus_general_api_client_request_reply)data->cb) (proxy, OUT_outut_int, OUT_output_garray, OUT_result, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_freedesktop_DBus_general_api_client_request_async (DBusGProxy *proxy, const gint IN_action_id, const gint IN_input_int, const GArray* IN_input_garray, org_freedesktop_DBus_general_api_client_request_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "client_request", org_freedesktop_DBus_general_api_client_request_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_INT, IN_action_id, G_TYPE_INT, IN_input_int, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), IN_input_garray, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_freedesktop_DBus_general_api */

G_END_DECLS
