// Generated by CoffeeScript 1.7.1
(function() {
  var msg, pubkey, publicKey, ursa;

  ursa = require('ursa');

  pubkey = "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDjVz84HLUOf0agqvAZi9Zmn+Lz\ngj0zfd4kMIXmT+3pHSdaj4gexSrvBPV3xCh0pCBdHV+p+B3J5K8YUzmxMg4+XJEK\nc5gk1t9K7FpJiIOXL6TKIkvUMx/ioppH2r4kon81uEDmA+41DPKfPb5wSZY0BHZv\n2eofOsH/I7IOTAUmxQIDAQAB\n-----END PUBLIC KEY-----";

  msg = 'Hello AireadFan';

  console.log('message: ' + msg);

  publicKey = ursa.createPublicKey(pubkey);

}).call(this);

//# sourceMappingURL=app2.map
